steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mysql-proxy:$COMMIT_SHA', '-f', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA', '-f', '.']
images: ['gcr.io/$PROJECT_ID/mysql-proxy:$COMMIT_SHA','gcr.io/$PROJECT_ID/wordpress:$COMMIT_SHA']
